name: Linting

on:
  # Triggers the workflow on push or pull request
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install tox
        run: pip install tox
      - name: Run style checks
        run: tox -e format -- inferno tests --check --diff
  # pylint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8
  #     - name: Install tox
  #       run: pip install tox
  #     - name: Run pylint through tox
  #       run: tox -e pylint
